export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';

export const FETCH_CURRENT_MOVIES_REQUEST = 'FETCH_CURRENT_MOVIES_REQUEST';
export const FETCH_CURRENT_MOVIES_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_CURRENT_MOVIES_FAIL = 'FETCH_SEARCH_FAIL';
